### ISSUE TITLE
Not able to view in browser

### ISSUE THREAD

**Issue by SamaniTheCEO** [SamaniTheCEO/KB-Beta#1]
less.min.js:13 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
f.doXHR @ less.min.js:13
(anonymous) @ less.min.js:13
f.loadFile @ less.min.js:13
i @ less.min.js:13
j @ less.min.js:13
(anonymous) @ less.min.js:13
m.refresh @ less.min.js:13
2.../less/default-options @ less.min.js:13
e @ less.min.js:13
a @ less.min.js:13
(anonymous) @ less.min.js:13
(anonymous) @ less.min.js:13
(anonymous) @ less.min.js:13
less.min.js:13 Access to XMLHttpRequest at 'file:///Users/samani/Web/Sites/KB-Beta/less/styles.less' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
f.doXHR @ less.min.js:13
(anonymous) @ less.min.js:13
f.loadFile @ less.min.js:13
i @ less.min.js:13
j @ less.min.js:13
(anonymous) @ less.min.js:13
m.refresh @ less.min.js:13
2.../less/default-options @ less.min.js:13
e @ less.min.js:13
a @ less.min.js:13
(anonymous) @ less.min.js:13
(anonymous) @ less.min.js:13
(anonymous) @ less.min.js:13
less.min.js:13 DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///Users/samani/Web/Sites/KB-Beta/less/styles.less'.
    at f.doXHR (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:7760)
    at file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:8460
    at new Promise (<anonymous>)
    at f.loadFile (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:8239)
    at i (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10309)
    at j (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10454)
    at file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:11956
    at new Promise (<anonymous>)
    at Object.m.refresh (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:11730)
    at Object.2.../less/default-options (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:2328)
less.min.js:13 Uncaught (in promise) TypeError: Cannot read property 'href' of undefined
    at less.min.js:13
    at less.min.js:13
(anonymous) @ less.min.js:13
(anonymous) @ less.min.js:13
Promise.catch (async)
i @ less.min.js:13
j @ less.min.js:13
(anonymous) @ less.min.js:13
m.refresh @ less.min.js:13
2.../less/default-options @ less.min.js:13
e @ less.min.js:13
a @ less.min.js:13
(anonymous) @ less.min.js:13
(anonymous) @ less.min.js:13
(anonymous) @ less.min.js:13
less.min.js:13 Access to XMLHttpRequest at 'file:///Users/samani/Web/Sites/KB-Beta/less/styles.less' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
f.doXHR @ less.min.js:13
(anonymous) @ less.min.js:13
f.loadFile @ less.min.js:13
i @ less.min.js:13
j @ less.min.js:13
(anonymous) @ less.min.js:13
setInterval (async)
k @ less.min.js:13
m.watch @ less.min.js:13
(anonymous) @ index.html:13
less.min.js:13 DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///Users/samani/Web/Sites/KB-Beta/less/styles.less'.
    at f.doXHR (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:7760)
    at file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:8460
    at new Promise (<anonymous>)
    at f.loadFile (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:8239)
    at i (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10309)
    at j (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10454)
    at file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10603
less.min.js:13 Uncaught (in promise) TypeError: Cannot read property 'href' of undefined
    at less.min.js:13
    at less.min.js:13
(anonymous) @ less.min.js:13
(anonymous) @ less.min.js:13
Promise.catch (async)
i @ less.min.js:13
j @ less.min.js:13
(anonymous) @ less.min.js:13
setInterval (async)
k @ less.min.js:13
m.watch @ less.min.js:13
(anonymous) @ index.html:13
less.min.js:13 Access to XMLHttpRequest at 'file:///Users/samani/Web/Sites/KB-Beta/less/styles.less' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
f.doXHR @ less.min.js:13
(anonymous) @ less.min.js:13
f.loadFile @ less.min.js:13
i @ less.min.js:13
j @ less.min.js:13
(anonymous) @ less.min.js:13
setInterval (async)
k @ less.min.js:13
m.watch @ less.min.js:13
(anonymous) @ index.html:13
less.min.js:13 DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///Users/samani/Web/Sites/KB-Beta/less/styles.less'.
    at f.doXHR (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:7760)
    at file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:8460
    at new Promise (<anonymous>)
    at f.loadFile (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:8239)
    at i (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10309)
    at j (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10454)
    at file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10603
less.min.js:13 Uncaught (in promise) TypeError: Cannot read property 'href' of undefined
    at less.min.js:13
    at less.min.js:13
(anonymous) @ less.min.js:13
(anonymous) @ less.min.js:13
Promise.catch (async)
i @ less.min.js:13
j @ less.min.js:13
(anonymous) @ less.min.js:13
setInterval (async)
k @ less.min.js:13
m.watch @ less.min.js:13
(anonymous) @ index.html:13
less.min.js:13 Access to XMLHttpRequest at 'file:///Users/samani/Web/Sites/KB-Beta/less/styles.less' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
f.doXHR @ less.min.js:13
(anonymous) @ less.min.js:13
f.loadFile @ less.min.js:13
i @ less.min.js:13
j @ less.min.js:13
(anonymous) @ less.min.js:13
setInterval (async)
k @ less.min.js:13
m.watch @ less.min.js:13
(anonymous) @ index.html:13
less.min.js:13 DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///Users/samani/Web/Sites/KB-Beta/less/styles.less'.
    at f.doXHR (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:7760)
    at file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:8460
    at new Promise (<anonymous>)
    at f.loadFile (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:8239)
    at i (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10309)
    at j (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10454)
    at file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10603
less.min.js:13 Uncaught (in promise) TypeError: Cannot read property 'href' of undefined
    at less.min.js:13
    at less.min.js:13
(anonymous) @ less.min.js:13
(anonymous) @ less.min.js:13
Promise.catch (async)
i @ less.min.js:13
j @ less.min.js:13
(anonymous) @ less.min.js:13
setInterval (async)
k @ less.min.js:13
m.watch @ less.min.js:13
(anonymous) @ index.html:13
less.min.js:13 Access to XMLHttpRequest at 'file:///Users/samani/Web/Sites/KB-Beta/less/styles.less' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
f.doXHR @ less.min.js:13
(anonymous) @ less.min.js:13
f.loadFile @ less.min.js:13
i @ less.min.js:13
j @ less.min.js:13
(anonymous) @ less.min.js:13
setInterval (async)
k @ less.min.js:13
m.watch @ less.min.js:13
(anonymous) @ index.html:13
less.min.js:13 DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///Users/samani/Web/Sites/KB-Beta/less/styles.less'.
    at f.doXHR (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:7760)
    at file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:8460
    at new Promise (<anonymous>)
    at f.loadFile (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:8239)
    at i (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10309)
    at j (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10454)
    at file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10603
less.min.js:13 Uncaught (in promise) TypeError: Cannot read property 'href' of undefined
    at less.min.js:13
    at less.min.js:13
(anonymous) @ less.min.js:13
(anonymous) @ less.min.js:13
Promise.catch (async)
i @ less.min.js:13
j @ less.min.js:13
(anonymous) @ less.min.js:13
setInterval (async)
k @ less.min.js:13
m.watch @ less.min.js:13
(anonymous) @ index.html:13
less.min.js:13 Access to XMLHttpRequest at 'file:///Users/samani/Web/Sites/KB-Beta/less/styles.less' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
f.doXHR @ less.min.js:13
(anonymous) @ less.min.js:13
f.loadFile @ less.min.js:13
i @ less.min.js:13
j @ less.min.js:13
(anonymous) @ less.min.js:13
setInterval (async)
k @ less.min.js:13
m.watch @ less.min.js:13
(anonymous) @ index.html:13
less.min.js:13 DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///Users/samani/Web/Sites/KB-Beta/less/styles.less'.
    at f.doXHR (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:7760)
    at file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:8460
    at new Promise (<anonymous>)
    at f.loadFile (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:8239)
    at i (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10309)
    at j (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10454)
    at file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10603
less.min.js:13 Uncaught (in promise) TypeError: Cannot read property 'href' of undefined
    at less.min.js:13
    at less.min.js:13
(anonymous) @ less.min.js:13
(anonymous) @ less.min.js:13
Promise.catch (async)
i @ less.min.js:13
j @ less.min.js:13
(anonymous) @ less.min.js:13
setInterval (async)
k @ less.min.js:13
m.watch @ less.min.js:13
(anonymous) @ index.html:13
less.min.js:13 Access to XMLHttpRequest at 'file:///Users/samani/Web/Sites/KB-Beta/less/styles.less' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
f.doXHR @ less.min.js:13
(anonymous) @ less.min.js:13
f.loadFile @ less.min.js:13
i @ less.min.js:13
j @ less.min.js:13
(anonymous) @ less.min.js:13
setInterval (async)
k @ less.min.js:13
m.watch @ less.min.js:13
(anonymous) @ index.html:13
less.min.js:13 DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///Users/samani/Web/Sites/KB-Beta/less/styles.less'.
    at f.doXHR (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:7760)
    at file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:8460
    at new Promise (<anonymous>)
    at f.loadFile (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:8239)
    at i (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10309)
    at j (file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10454)
    at file:///Users/samani/Web/Sites/KB-Beta/js/less.min.js:13:10603
less.min.js:13 Uncaught (in promise) TypeError: Cannot read property 'href' of undefined
    at less.min.js:13
    at less.min.js:13
(anonymous) @ less.min.js:13
(anonymous) @ less.min.js:13
Promise.catch (async)
i @ less.min.js:13
j @ less.min.js:13
(anonymous) @ less.min.js:13
setInterval (async)
k @ less.min.js:13
m.watch @ less.min.js:13
(anonymous) @ index.html:13

**Comment by SamaniTheCEO** [comment]
adding less.js requires us to run this project on a live server.
